"""
Backend constants
"""
CONFIDENCE_THRESHOLD = 0.5
PIC_CLASS_LABELS = ["HDPE", "LDPE", "EPS", "PET", "PP", "PS", "UPC/PVC"]
ARL_CLASS_LABELS = ["R", "CR", "NR", "CL"]
TARGET_IMAGE_SIZE = (640, 640)
OUTPUT_IMAGE_FORMAT = "JPEG"
